global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rag-auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rag-auth:8081']

  - job_name: 'rag-document-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rag-document:8082']

  - job_name: 'rag-embedding-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rag-embedding:8083']

  - job_name: 'rag-core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rag-core:8084']

  - job_name: 'rag-admin-service'
    metrics_path: '/admin/api/actuator/prometheus'
    static_configs:
      - targets: ['rag-admin:8085']