# Service Accounts with Workload Identity annotations
# These are created by 12-setup-gke-cluster.sh, but defined here for reference

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-auth
  namespace: rag-system
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-sa@byo-rag-dev.iam.gserviceaccount.com
  labels:
    app: rag-auth
    app.kubernetes.io/name: rag-auth
    app.kubernetes.io/part-of: rag-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-document
  namespace: rag-system
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-sa@byo-rag-dev.iam.gserviceaccount.com
  labels:
    app: rag-document
    app.kubernetes.io/name: rag-document
    app.kubernetes.io/part-of: rag-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-embedding
  namespace: rag-system
  annotations:
    iam.gke.io/gcp-service-account: pubsub-sa@byo-rag-dev.iam.gserviceaccount.com
  labels:
    app: rag-embedding
    app.kubernetes.io/name: rag-embedding
    app.kubernetes.io/part-of: rag-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-core
  namespace: rag-system
  annotations:
    iam.gke.io/gcp-service-account: pubsub-sa@byo-rag-dev.iam.gserviceaccount.com
  labels:
    app: rag-core
    app.kubernetes.io/name: rag-core
    app.kubernetes.io/part-of: rag-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-admin
  namespace: rag-system
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-sa@byo-rag-dev.iam.gserviceaccount.com
  labels:
    app: rag-admin
    app.kubernetes.io/name: rag-admin
    app.kubernetes.io/part-of: rag-system
